spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: 123456

logging:
  level:
    root: info
    com.macro.mall: debug