spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 123456

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info